### PR TITLE
[Fixed] Typos and Grammatical Errors. 

### PR DESCRIPTION
**Pull request by syedsohan**
There were quite a few typos and grammatical errors in multiple `.md files` which are now fixed.

### CODE REVIEW

**Comment by FrancescoXX** [comment]
Thank you!

**Comment by FrancescoXX** [comment]
Thank you!

**Comment by syedsohan** [comment]
> Thank you!

It was the least I could do! :slightly_smiling_face:

**Comment by syedsohan** [comment]
> Thank you!

It’s my pleasure!

**Pull request merged**
