### PR TITLE
fixing issue 212 - Merge 'Integration' section in the main bookmarks doc

### PR DESCRIPTION
**Pull request by paaggeli**

### CODE REVIEW

**Comment by FrancescoXX** [comment]
can you please explain the change? please only do PRs relative to issue that havbe been accepted and ssigned, thanks

**Comment by paaggeli** [comment]
Bookmarks
As the issue's description, I merged the integration section into the main bookmarks, located under 'Key Features -> Bookmarks.'
Since the integration section has been merged, I removed it from the sidebar. 
However, this caused an inconsistency in the sidebar position for 'For Content Creators,' 'For OSS Contributors,' and 'Community.' So, I changed their positions. 
I also had to make some CSS changes to display the correct icons.

**Comment by FrancescoXX** [comment]
thanks, the branch has conflicts, do you mind solving them?

**Comment by paaggeli** [comment]
Conflict resolved, ready for review.

**Comment by FrancescoXX** [comment]
hei @paaggeli , send a dm to https://twitter.com/FrancescoCiull4 so we can send you some swag

**Pull request merged**
