### PR TITLE
Corrected the grammer error in reputation.md

### PR DESCRIPTION
**Pull request by sarojregmi200**
I found a error while going throught the docs and then I corrected it and though there might be more errors so, I used the bing AI to find more errors.

All the changes that I have made are checked by me and passed by me.

### CODE REVIEW

**Comment by sarojregmi200** [comment]
@FrancescoXX Please, kindly review the pr.

**Review by m-krebs — COMMENTED** [review]
In line 16 the first comma isn't needed

**Comment by sarojregmi200** [comment]
I believe it is fine with or without a comma, @m-krebs

**Comment by m-krebs** [comment]
@sarojregmi200 I just read it and it felt a little bit weird, so I checked against "Quillbot" and "Languagetool" grammar checkers and both suggested to remove it. But it's up to you :)

**Comment by sarojregmi200** [comment]
Thank you, for pointing that out but once you pointed that the comma was unnecessary. I checked it using Grammarly and found nothing wrong. I will change it though. Since, the check against two grammar tools suggested so.

**Pull request merged**
